name: blindspot-report
description: 일일 지식 사각지대 보고서
enabled: true
tags: ["hippocampus", "blindspot"]
triggers:
  - type: scheduled
    every: 24h
steps:
  - name: scan_domains
    type: elasticsearch.esql.query
    with:
      query: |
        FROM knowledge-domains
        | EVAL density = memory_count * avg_confidence,
               staleness = DATE_DIFF("day", last_updated, NOW())
        | WHERE density < 3.0 OR staleness > 30
        | SORT density ASC

  - name: generate_report
    type: ai.completion
    with:
      prompt: |
        다음 지식 사각지대 분석 결과를 바탕으로 일일 보고서를 작성하라.

        ## 분석 데이터
        {{ steps.scan_domains.output }}

        ## 보고서 포함 항목
        1. **위험 영역 (VOID)**: 경험 데이터가 전무한 도메인. 즉시 주의 필요.
        2. **취약 영역 (SPARSE)**: 경험이 부족한 도메인. 추가 학습 권장.
        3. **노후 영역 (Stale)**: 30일 이상 업데이트 없는 도메인. 재검증 필요.
        4. **개선 권고사항**: 각 영역별 구체적 조치 방안.
        5. **우선순위**: 위험도 기준 정렬된 조치 리스트.

        ## 출력 형식
        마크다운 형식의 구조화된 보고서를 작성하라.
        각 도메인의 density, staleness, status를 명시하라.

  - name: store_report
    type: elasticsearch.index
    with:
      index: memory-access-log
      document:
        timestamp: "{{ now }}"
        action: blindspot_report
        query: "daily blindspot scan"
        experience_grade: "REPORT"
        blindspot_triggered: true
        relevance_score: 0.0
