name: remember-memory
description: 새로운 경험을 episodic + semantic 메모리에 저장
enabled: true
tags: ["hippocampus", "memory"]
triggers:
  - type: manual
inputs:
  - name: raw_text
    type: string
    description: "원본 텍스트 (에피소드 기억)"
  - name: entity
    type: string
    description: "엔티티 이름 (예: payment-service)"
  - name: attribute
    type: string
    description: "속성 이름 (예: db-connection-pool-size)"
  - name: value
    type: string
    description: "속성 값"
  - name: confidence
    type: string
    description: "신뢰도 (0.0~1.0)"
  - name: category
    type: string
    description: "카테고리 (예: database, kubernetes)"
  - name: conversation_id
    type: string
    description: "대화 ID"
steps:
  - name: store_episodic
    type: elasticsearch.index
    with:
      index: episodic-memories
      document:
        raw_text: "{{ inputs.raw_text }}"
        content: "{{ inputs.raw_text }}"
        conversation_id: "{{ inputs.conversation_id }}"
        timestamp: "{{ now }}"
        importance: "{{ inputs.confidence }}"
        category: "{{ inputs.category }}"
        source_type: conversation
        reflected: false

  - name: store_semantic
    type: elasticsearch.index
    with:
      index: semantic-memories
      document:
        content: "{{ inputs.entity }} {{ inputs.attribute }} {{ inputs.value }}"
        entity: "{{ inputs.entity }}"
        attribute: "{{ inputs.attribute }}"
        value: "{{ inputs.value }}"
        confidence: "{{ inputs.confidence }}"
        category: "{{ inputs.category }}"
        source_conversation_ids:
          - "{{ inputs.conversation_id }}"
        first_observed: "{{ now }}"
        last_updated: "{{ now }}"
        update_count: 1

  - name: update_domain
    type: elasticsearch.index
    with:
      index: knowledge-domains
      document:
        domain: "{{ inputs.category }}"
        last_updated: "{{ now }}"
